### ISSUE TITLE
5.9 Regression: Inferring global actor from curried initializer

### ISSUE THREAD

**Issue by KeithBauerANZ** [apple/swift#67581]
**Description**

```swift
@MainActor
struct S {}

func acceptMAF<T>(_: @MainActor () -> T) {}

acceptMAF(S.init)
```

This compiles with Swift 5.8, but not with Swift 5.9 from Xcode 15b5:

```
CurriedInferMainActor.swift:6:11: error: call to main actor-isolated initializer 'init()' in a synchronous nonisolated context
acceptMAF(S.init)
          ^
CurriedInferMainActor.swift:2:8: note: calls to initializer 'init()' from outside of its actor context are implicitly asynchronous
struct S {}
       ^
```

This worked with the Swift 5.9 from Xcode 15b4.
Replacing the offending line with the equivalent `acceptMAF { S() }` works on all Swift versions tested.

**Environment**
swift-driver version: 1.87 Apple Swift version 5.9 (swiftlang-5.9.0.124.4 clang-1500.0.38.1)
Target: arm64-apple-macosx13.0

**Comment by hborla** [comment]
This doesn't happen under `-strict-concurrency=complete` and `-swift-version 6`. It appears to only not work under `-strict-concurrency=minimal`
