### ISSUE TITLE
[Regression] 5.7 – "cannot reference invalid declaration" error when accessing property wrapper inside closure

### ISSUE THREAD

**Issue by pablocornejo** [apple/swift#61017]
**Describe the bug**
Accessing a property wrapper using the underscore notation in a closure does not compile with Swift 5.7 (Xcode 14 RC).

This code reproduces the issue:

```swift
@propertyWrapper
struct Wrapper {
    var wrappedValue: Int
    
    init(wrappedValue: Int) {
        self.wrappedValue = wrappedValue
    }
}

class Foo {
    let bar: () -> Void = {
        @Wrapper var wrapped = 1
        
        let wrapper = _wrapped // compiles on 5.6, errors out on 5.7
    }
}

```

**Steps To Reproduce**
1. Add the code above to a Wrapper.swift file
2. Compile the file with the Swift 5.7 compiler: `swiftc Wrapper.swift`
3. The following compilation error occurs: 
```
❯ swiftc Wrapper.swift
Wrapper.swift:14:23: error: cannot reference invalid declaration '_wrapped'
        let wrapper = _wrapped // compiles on 5.6, errors out on 5.7
                      ^
Wrapper.swift:12:22: note: '_wrapped' declared here
        @Wrapper var wrapped = 1
```

**Expected behavior**
Accessing the property wrapper using the underscore notation code should compile, as it does on Swift 5.6.

**Environment**
 - Xcode 14 RC toolchain

**Additional context**
The same code produces a SILGen crash with the 5.7 nightly toolchain: https://godbolt.org/z/o1qGnov7o

```
unsupported collection upcast kind
UNREACHABLE executed at /home/build-user/swift/lib/SILGen/SILGenPoly.cpp:523!
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/swift-5.7/usr/bin/swift-frontend -frontend -S -primary-file <source> -target x86_64-unknown-linux-gnu -disable-objc-interop -g -new-driver-path /opt/compiler-explorer/swift-5.7/usr/bin/swift-driver -empty-abi-descriptor -resource-dir /opt/compiler-explorer/swift-5.7/usr/lib/swift -enable-anonymous-context-mangled-names -Xllvm --x86-asm-syntax=intel -module-name output -o /app/output.s
1.	Swift version 5.7.1-dev (LLVM 7e31b78ab3255fa, Swift 1e80674d67f5505)
2.	Compiling with the current language version
3.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for file "<source>")
4.	While silgen emitStoredPropertyInitialization SIL function "@$s6output3FooC3baryycvpfi".
 for expression at [<source>:11:27 - line:15:5] RangeText="{
        @Wrapper var wrapped = 1
        
        let wrapper = _wrapped // works on 5.6, crashes on 5.7
    "
5.	While silgen closureexpr SIL function "@$s6output3FooC3baryycvpfiyycfU_".
 for expression at [<source>:11:27 - line:15:5] RangeText="{
        @Wrapper var wrapped = 1
        
        let wrapper = _wrapped // works on 5.6, crashes on 5.7
    "

...

Compiler returned: 139
```

**Comment by xedin** [comment]
I think this has been fixed by https://github.com/apple/swift/pull/60409. Could you please use 5.7 or main toolchains to verify?

**Comment by xedin** [comment]
Ok I see, looks like this is a different problem after all.

**Comment by pablocornejo** [comment]
Yes, this seems to still be crashing on main: https://godbolt.org/z/K6W58PKPa
