### ISSUE TITLE
[Source compatibility suite] penny-bot failing to build with 5.9 branch on macOS

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#71316]
### Description

The [penny-bot](https://github.com/vapor/penny-bot.git) project is failing to build with the 5.9 branch on macOS. The error seen in the log is
```
penny-bot/.build/checkouts/DiscordBM/Sources/DiscordModels/Types/Channel.swift:10:17: error: external macro implementation type 'UnstableEnumMacro.UnstableEnum' could not be found for macro 'UnstableEnum()'
```

### Reproduction

```swift
swift build --disable-sandbox --package-path penny-bot --verbose --configuration release -Xswiftc -swift-version -Xswiftc 5
```

### Expected behavior

Expected behavior
Expect the project to build

### Environment

Apple Swift version 5.9.2-dev (LLVM 2b42c5ce063a374, Swift 9067148bc9c9a72)
Target: x86_64-apple-macosx10.15.4

### Additional information

https://ci.swift.org/view/Swift%205.9/job/swift-5.9-source-compat-suite/199/
