### ISSUE TITLE
Swift Compiler 5.8 / Xcode 14.3 RC not compiling with Modules built on Swift 5.7.2

### ISSUE THREAD

**Issue by seanreinhardtapps** [apple/swift#64552]
**Description**
Swift Compiler 5.8 / Xcode 14.3 RC not compiling with Modules built on Swift 5.7.2

**Steps to reproduce**
- Build XCFramework on Xcode 14.2, set `BUILD_LIBRARY_FOR_DISTRIBUTION=Yes`
- Add product to App, build on Xcode 14.3

**Expected behavior**
Framework built on earlier Swift Compiler, with `BUILD_LIBRARY_FOR_DISTRIBUTION=Yes`, should compile with later version of Swift Compiler

**Actual behavior**
Compilation Error: 
```
Failed to build module 'HyprMX'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.8 (swiftlang-5.8.0.124.1 clang-1403.0.22.11.100)'). Please select a toolchain which matches the SDK.
```

**Environment - App**
- Swift compiler version info swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.1 clang-1403.0.22.11.100)
- Xcode version info Version 14.3 (14E222a)
- Deployment target: 13.0

**Environment - XCFramework Build**
- Swift compiler version info swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
- Xcode version info Version 14.2 (14C18)
- Deployment target: 9.0

**Additional Errors**
multiple cases of:
```
'MainActor' is only available in iOS 13.0 or newer
```

**Swiftinterface**
```
// swift-interface-format-version: 1.0
// swift-compiler-version: Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
// swift-module-flags: -target arm64-apple-ios9.0-simulator -enable-objc-interop -enable-library-evolution -swift-version 5 -enforce-exclusivity=checked -O -module-name HyprMX
// swift-module-flags-ignorable: -enable-bare-slash-regex
import AdSupport
import AppTrackingTransparency
import Combine
import CoreTelephony
import Foundation
@_exported import HyprMX
import HyprMX_Private
import Network
import SafariServices
import StoreKit
import Swift
import UIKit
import _Concurrency
import _StringProcessing
@objc public protocol HyprMXBannerDelegate {
  @objc optional func adDidLoad(_ bannerView: HyprMXBannerView)
  @objc optional func adFailed(toLoad bannerView: HyprMXBannerView, error: Error)
  @objc optional func adDidOpen(_ bannerView: HyprMXBannerView)
  @objc optional func adDidClose(_ bannerView: HyprMXBannerView)
  @objc optional func adWasClicked(_ bannerView: HyprMXBannerView)
  @objc optional func adWillLeaveApplication(_ bannerView: HyprMXBannerView)
}
@objc @_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers @_Concurrency.MainActor(unsafe) public class HyprMXBannerView : UIView {
  @objc @_Concurrency.MainActor(unsafe) public var placementName: String? {
    @objc get
    @objc set
  }
  @objc @_Concurrency.MainActor(unsafe) public var adSize: CGSize {
    @objc get
    @objc set
  }
  @objc @_Concurrency.MainActor(unsafe) weak public var placementDelegate: HyprMXBannerDelegate?
  @_Concurrency.MainActor(unsafe) @objc override dynamic public var isHidden: Bool {
    @objc get
    @objc set
  }
  @objc @_Concurrency.MainActor(unsafe) convenience public init(placementName: String, adSize: CGSize)
  @objc @_Concurrency.MainActor(unsafe) public func adTapped()
  @_Concurrency.MainActor(unsafe) @objc override dynamic public init(frame: CGRect)
  @objc deinit
  @_Concurrency.MainActor(unsafe) @objc override dynamic public func didMoveToSuperview()
  @_Concurrency.MainActor(unsafe) @objc override dynamic public func layoutSubviews()
  @objc @_Concurrency.MainActor(unsafe) public func loadAd()
}
extension HyprMXBannerView : UIGestureRecognizerDelegate {
  @_Concurrency.MainActor(unsafe) @objc dynamic public func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldReceive touch: UITouch) -> Bool
  @_Concurrency.MainActor(unsafe) @objc dynamic public func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool
}

```

**Comment by stonko1994** [comment]
Any update on this? We are observing the same issue.

**Comment by Fushj89** [comment]
@stonko1994   https://github.com/apple/swift/pull/64412  may be solved

**Comment by a-szotyori** [comment]
We started seeing this issue again with Xcode 14.3.1 (14E300c):
```
Failed to build module 'GiniCaptureSDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)'). Please select a toolchain which matches the SDK.
```

We are [building our XCFrameworks](https://github.com/gini/gini-mobile-ios/blob/main/.github/workflows/bank-sdk.build.xcframeworks.yml) with `SKIP_INSTALL=NO` and `BUILD_LIBRARIES_FOR_DISTRIBUTION=YES`.
