### ISSUE TITLE
Failed to produce diagnostic for expression

### ISSUE THREAD

**Issue by mr-swifter** [apple/swift#60485]
**Describe the bug**
Xcode tells me to report a problem, the same if I compile with `swift build`

**Steps To Reproduce**
Problem can be reproduced with next small code snippet:
```
public struct Settings {
    public internal(set) var dictionary = [String: String]()
}

public struct Test {
    public internal(set) var dictionary = [String: String]()
    
    public init(settings: Settings) {
        for (key, value) in settings {
            
        }
    }
}
```
```
~/Dev/test/ swift --version
swift-driver version: 1.62.3 Apple Swift version 5.7 (swiftlang-5.7.0.123.8 clang-1400.0.29.50)
Target: arm64-apple-macosx12.0
~/Dev/test/ swift build
Building for debugging...
/Users/me/Dev/test/Sources/test/test.swift:9:9: error: failed to produce diagnostic for expression; please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project
        for (key, value) in settings {
        ^
```

**Expected behavior**
This works fine if I compile with Swift 5.6 and produce compilation error:
```
~/Dev/test/ swift build     
Building for debugging...
/Users/me/Dev/test/Sources/test/test.swift:9:29: error: tuple pattern cannot match values of non-tuple type '_'
        for (key, value) in settings {
                            ^
/Users/me/Dev/test/Sources/test/test.swift:9:29: error: for-in loop requires 'Settings' to conform to 'Sequence'
        for (key, value) in settings {
                            ^~~~~~~~
```

**Environment (please fill out the following information)**
 - OS: macOS 12.5 (21G72)
 - Xcode Version/Tag/Branch: Xcode 14 beta 5
 - Swift compiler: (see steps to reproduce)

**Comment by LucianoPAlmeida** [comment]
This is fixed on main by https://github.com/apple/swift/pull/60062
@ahoppen @xedin Was it cherry-picked to 5.7?

**Comment by xedin** [comment]
@LucianoPAlmeida #60062 is main only unfortunately.

**Comment by LucianoPAlmeida** [comment]
Ah ok, Thanks @xedin!

**Comment by LucianoPAlmeida** [comment]
Was checking if GitHub would close this by a `Resolves:#{number}` after merging or the PR, looks like not =[
But I guess we can close this
