### ISSUE TITLE
[Source compatibility suite] swift-testing failing to build on MacOs with 5.10 & 5.9

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#69278]
**Description**
The [swift-testing](https://github.com/apple/swift-testing) project is failing to build on MacOs with the 5.10 and 5.9 toolchains using Xcode 14.2. The error seen in the log is
```
swift-testing/Sources/TestingInternals/Discovery.cpp:227:38: error: variable does not have a constant initializer
  static constinit SWTMachHeaderList machHeaders;
                                     ^~~~~~~~~~~
swift-testing/Sources/TestingInternals/Discovery.cpp:227:10: note: required by 'constinit' specifier here
  static constinit SWTMachHeaderList machHeaders;
         ^~~~~~~~~
swift-testing/Sources/TestingInternals/Discovery.cpp:227:38: note: non-constexpr constructor 'vector' cannot be used in a constant expression
  static constinit SWTMachHeaderList machHeaders;
                                     ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/vector:519:5: note: declared here
    vector() _NOEXCEPT_(is_nothrow_default_constructible<allocator_type>::value)
    ^
```

* [Build log](https://ci.swift.org/view/Swift%205.10/job/swift-5.10-source-compat-suite/35/artifact/swift-source-compat-suite/FAIL_swift-testing_5.0_BuildSwiftPackage.log)

**Steps to reproduce**
To reproduce the issue, you can use the [source compatibility suite](https://github.com/apple/swift-source-compat-suite) and run
```
./runner.py --swift-branch release/5.10 --projects projects.json --include-actions 'action.startswith("Build")' --include-repos 'path == "swift-testing"' --swiftc <PATH_TO_5.10_COMPILER>
```

**Expected behavior**
The project should build fine

**Environment**
```
Apple Swift version 5.10-dev (LLVM 42340bb0680eb64, Swift ec16d2c831fffdc)
Target: x86_64-apple-macosx10.15
```
https://ci.swift.org/view/Swift%205.10/job/swift-5.10-source-compat-suite/35/
