### ISSUE TITLE
Autoclosures and global actors don't work together

### ISSUE THREAD

**Issue by KeithBauerANZ** [apple/swift#67688]
**Description**

```swift
func acceptAutoclosure(_ closure: @autoclosure @MainActor () -> ()) {}

@MainActor
func f() {}

acceptAutoclosure(f())
```

```
> swiftc AutoclosureIsolation.swift
AutoclosureIsolation.swift:6:19: error: call to main actor-isolated global function 'f()' in a synchronous nonisolated context
acceptAutoclosure(f())
                  ^
AutoclosureIsolation.swift:4:6: note: calls to global function 'f()' from outside of its actor context are implicitly asynchronous
func f() {}
     ^
```

I can see that you might want to reject this code (in which case there should be a different error on line 1, about global actors and autoclosures being incompatible), or accept it (in which case there shouldn't be an error at all), but either way, there's a bug here.

**Environment**
swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0

**Comment by KeithBauerANZ** [comment]
The snippet above compiles with Swift 6.2:

swift-driver version: 1.127.4.2 Apple Swift version 6.2 (swiftlang-6.2.0.9.909 clang-1700.3.9.907)
Target: arm64-apple-macosx15.0
