### ISSUE TITLE
[Concurrency] `multiple definition of 'swift::threading::fatal'` after new Threading library

### ISSUE THREAD

**Issue by kateinoigakukun** [apple/swift#59444]
**Describe the bug**
`multiple definition of 'swift::threading::fatal(char const*, ...)'` linking failure happens since https://github.com/apple/swift/pull/59287

**To Reproduce**

Follow the below steps.

```
$ cat main.swift
import Dispatch

@main
struct Main {
  static func main() async {}
}

$ /home/katei/.ghq/github.com/kylef/swiftenv/versions/DEVELOPMENT-SNAPSHOT-2022-06-13-a/usr/bin/swiftc -parse-as-library -static-stdlib
error: link command failed with exit code 1 (use -v to see invocation)
/usr/bin/ld.gold: error: /home/katei/.ghq/github.com/kylef/swiftenv/versions/DEVELOPMENT-SNAPSHOT-2022-06-13-a/usr/lib/swift_static/linux/libswiftCore.a(Errors.cpp.o): multiple definition of 'swift::threading::fatal(char const*, ...)'
/usr/bin/ld.gold: /home/katei/.ghq/github.com/kylef/swiftenv/versions/DEVELOPMENT-SNAPSHOT-2022-06-13-a/usr/lib/swift_static/linux/libswift_Concurrency.a(ThreadingError.cpp.o): previous definition here
```

**Expected behavior**

No link failure

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Swift Version: `DEVELOPMENT-SNAPSHOT-2022-06-13-a`

**Comment by kateinoigakukun** [comment]
CC: @al45tair

**Comment by al45tair** [comment]
My guess is that `gold` is sensitive to the link order in this case; it'll be happening because the main runtime's version of this function is implemented in the same object file as a number of other functions that are absolutely required, whereas the Concurrency runtime's version was in its own object. If the linker includes the one from the Concurrency runtime first, you'll get this error because it _has to_ link the object from the main runtime. The fix is to pull the threading error function out into its own object in the main runtime as well, which is what I've done in #59457.
