### ISSUE TITLE
Macro definition breaks dictionary compilation

### ISSUE THREAD

**Issue by keith** [apple/swift#66648]
This code:

```swift
import Foundation

@freestanding(expression) macro URL(_ stringLiteral: String) -> URL =
    #externalMacro(module: "a", type: "URLMacro")

func foo() {
    var broken = [URL: String]()
}
```

Fails to compile with:

```
/tmp/foo.swift:7:18: error: type 'URL.Type' cannot conform to 'Hashable'
    var broken = [URL: String]()
                 ^
/tmp/foo.swift:7:18: note: only concrete types such as structs, enums and classes can conform to protocols
    var broken = [URL: String]()
                 ^
/tmp/foo.swift:7:18: note: required by generic struct 'Dictionary' where 'Key' = 'URL.Type'
    var broken = [URL: String]()
                 ^
/tmp/foo.swift:7:18: error: cannot call value of non-function type '[URL.Type : String.Type]'
    var broken = [URL: String]()
                 ^            ~~
```

**Steps to reproduce**

- `swiftc /tmp/foo.swift`

**Environment**
- Xcode 15.0 beta 1

**Comment by grynspan** [comment]
@DougGregor I believe there's a fix on trunk for this already?

**Comment by keith** [comment]
This still fails to compile with Xcode 15.0 RC 1 (15A240d), I haven't verified in a snapshot
