### ISSUE TITLE
[Source compatibility suite] SwiftLint failing to build - new Swift parser generated errors for code that C++ parser accepted

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#63269]
**Describe the bug**
The SwfitLint project is failing to build with swift 5.0

From the build logs you can see 
```
/Users/ec2-user/jenkins/workspace/swift-main-source-compat-suite/swift-source-compat-suite/project_cache/SwiftLint/Tests/SwiftLintFrameworkTests/IntegrationTests.swift:19:54: error: unexpected code '== $0.path' in closure
        XCTAssert(swiftFiles.contains(where: { #file == $0.path }), "current file should be included")
                                                     ^~~~~~~~~~~
/Users/ec2-user/jenkins/workspace/swift-main-source-compat-suite/swift-source-compat-suite/project_cache/SwiftLint/Tests/SwiftLintFrameworkTests/IntegrationTests.swift:1:1: error: new Swift parser generated errors for code that C++ parser accepted
import Foundation
```
https://ci.swift.org/job/swift-main-source-compat-suite/313/

**Expected behavior**
Expecting the project to build correctly

**Environment**
```
'swift-driver': Apple Swift version 5.9-dev (LLVM 9c08d218ae741f4, Swift 35553d93068bb2f)
```

**Comment by AnthonyLatsis** [comment]
cc @ahoppen
