### ISSUE TITLE
[SR-9686] Swift 5 regression: extension applied to type alias not "seen"

### ISSUE THREAD

**Issue by ktoso** [apple/swift#52128]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9686      |
   |Radar             | rdar://problem/47352138         |
   |Original Reporter | @ktoso      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, 5.0Regression, SourceCompatibility        |
   |Assignee          | @slavapestov      |
   |Priority          | Medium      |

   

   md5: e92e8c40edeaa38d9111378b8f591e2e

  </details>

**is duplicated by**:  
* [SR-9671](https://bugs.swift.org/browse/SR-9671) compiler crash: expression has no type / (declref_expr type='<null>' decl=Logging.(file). extension.init(stringLiteral:)  

**Issue Description:**

I believe I found a regression in Swift 5 ( 5.0-DEVELOPMENT-SNAPSHOT-2019-01-16-a ) with regards to 4.2 while working on the logging proposal for the server side swift working group (so context is: <https://github.com/weissi/swift-server-logging-api-proposal> ).

 

I'm using these types in a library which is cross compiled for 4.2 and development builds of Swift 5 so noticed it there. The following self contained snippet isolates the issue:

 

``` java
public enum Logging {
}

public extension Logging {
    typealias Metadata = [String: MetadataValue]

    enum MetadataValue {
        case string(String)
        case array([Metadata.Value])
    }
}


extension Logging.Metadata.Value: Equatable {
    // we have to implement it, in reality there's many more cases in the enum
    public static func ==(lhs: Logging.Metadata.Value, rhs: Logging.Metadata.Value) -> Bool {
        switch (lhs, rhs) {
        case (.string(let lhs), .string(let rhs)):
            return lhs == rhs
        case (.array(let lhs), .array(let rhs)):
            return lhs == rhs
        default:
            return false
        }
    }
}
```

The important bit being that we extend \`Logging.Metadata.Value\` via the alias through \`Metadata\`. This works on swift 4.2 but not on 5:

``` java
$ swiftenv local 4.2.1
$ swiftc repro.swift


$ swiftenv local 5.0-DEVELOPMENT-SNAPSHOT-2019-01-16-a
$ swiftc repro.swift
repro.swift:29:24: error: type 'Logging.Metadata.Value' (aka 'Logging.MetadataValue') does not conform to protocol 'Equatable'
            return lhs == rhs
                       ^
repro.swift:29:24: error: '<Self where Self : Equatable> (Self.Type) -> (Self, Self) -> Bool' requires that 'Logging.Metadata.Value' (aka 'Logging.MetadataValue') conform to 'Equatable'
            return lhs == rhs
                       ^
repro.swift:29:24: note: requirement specified as 'Logging.Metadata.Value' (aka 'Logging.MetadataValue') : 'Equatable'
            return lhs == rhs
                       ^
repro.swift:29:24: note: requirement from conditional conformance of '[Logging.Metadata.Value]' (aka 'Array<Logging.MetadataValue>') to 'Equatable'
            return lhs == rhs
                       ^
```

If we avoid touching the alias it works on all Swift versions:

``` java
// NOPE: extension Logging.Metadata.Value: Equatable {
// yes:
extension Logging.MetadataValue: Equatable {
```

I would hope to be able to use the alias version since this way we have an uniform way to address Key/Value, by always saying `Logging.Metadata.Key` / `Logging.Metadata.Value` etc.

**Comment by slavapestov** [comment]
Behaves correctly in 5.7:

```swift
/private/tmp/SR-9671/swift-server-logger-api/Sources/Logging/Logging.swift:295:1: error: extension of type 'Logging.Metadata.Value' (aka 'Logging.MetadataValue') must be declared as an extension of 'Logging.MetadataValue'
extension Logging.Metadata.Value: ExpressibleByStringInterpolation {
^         ~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/SR-9671/swift-server-logger-api/Sources/Logging/Logging.swift:295:1: note: did you mean to extend 'Logging.MetadataValue' instead?
extension Logging.Metadata.Value: ExpressibleByStringInterpolation {
^         ~~~~~~~~~~~~~~~~~~~~~~
          Logging.MetadataValue
```
