### ISSUE TITLE
Freestanding Declaration Macro Expanding Defer Block Causes Compiler Error starting with Swift 5.10

### ISSUE THREAD

**Issue by i2h3** [apple/swift#72307]
### Description

With Swift 5.9, I implemented a Swift package which provides a freestanding declaration macro. That macro expands to two variable declarations and a `defer` block to start a signpost and define its end in the `defer` block immediately. It always compiled and worked fine. After updating to Swift 5.10, the expansion causes a compiler error.

### Reproduction

I have set up an example Swift macro package which implements the minimal example. I will update this issue after creation with the URL to the GitHub repository because I want to have an issue number for it first.

It builds and works fine in Swift 5.9 (Xcode 15.2).

It results in a compiler error in Swift 5.10 (Xcode 15.3) at the `defer` block of the macro expansion.

```plain
$ swift build            
Building for debugging...
/var/folders/5h/qlnrjvt16p31yv1ndyt_sll00000gn/T/swift-generated-sources/@__swiftmacro_14SignpostClient7ExampleC8sayHelloyyF8signpostfMf0_.swift:4:1: error: expected macro expansion to produce a declaration
defer {
^
/Users/redacted/Temporary/Signpost/Sources/SignpostClient/main.swift:9:9: note: in expansion of macro 'signpost' here
        #signpost
        ^~~~~~~~~
/var/folders/5h/qlnrjvt16p31yv1ndyt_sll00000gn/T/swift-generated-sources/@__swiftmacro_14SignpostClient7ExampleC8sayHelloyyF8signpostfMf0_.swift:2:5: warning: initialization of immutable value 'signpostIntervalState' was never used; consider replacing with assignment to '_' or removing it
let signpostIntervalState = signposter.beginInterval(#function, id: signpostID)
    ^
/Users/redacted/Temporary/Signpost/Sources/SignpostClient/main.swift:9:9: note: in expansion of macro 'signpost' here
        #signpost
        ^~~~~~~~~
error: fatalError
```

<img width="1052" alt="Screenshot" src="https://github.com/apple/swift/assets/142165879/327daff0-b945-4eac-8a27-c26bf94de39c">

### Expected behavior

The macro expansion is accepted and does not cause a compiler error as before.

### Environment

```plain
$ swiftc -version
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
```

### Additional information

I asked about this issue already [in the Swift forums](https://forums.swift.org/t/how-to-expand-freestanding-declaration-macro-with-a-defer-block/70465/2).

**Comment by shimastripe** [comment]
It looks like it was intentional changes. https://github.com/apple/swift/pull/69106

And, I think it seems appropriate to use [CodeItem freestanding macro](https://github.com/apple/swift-evolution/blob/main/proposals/0397-freestanding-declaration-macros.md#code-item-macros) for your case. But CodeItem macro is experimental feature yet... https://github.com/apple/swift/pull/65427
Just sharing 🙏

**Comment by i2h3** [comment]
Thank you for point out, I considered it being intentional. Ok, then I will have to wait for the CodeItem macro, I guess.
