### ISSUE TITLE
[Source compatibility suite] Result failing to build with main branch

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#70970]
### Description

The [Result](https://github.com/antitypical/Result/tree/master) project  is failing to build with the main branch. The error seen in the log is
```
Result/Result/Result.swift:87:14: error: ambiguous use of 'get()'
                return try get()
                           ^
Result/Result/Result.swift:95:14: note: found this candidate 
        public func get() throws -> Success {
                    ^
Swift.Result:8:28: note: found this candidate in module 'Swift'
    @inlinable public func get() throws(Failure) -> Success
                           ^
error: fatalError
```

This was seemingly introduced with https://github.com/apple/swift/commit/7d74b3ba5c0f66d630cee8652263979eeed11289

### Reproduction

```
swift build --disable-sandbox --package-path Result --verbose --configuration debug --build-tests -Xswiftc -swift-version -Xswiftc 5 -Xswiftc -enable-testing
```

### Expected behavior

Expect the project to build

### Environment

```swift
Apple Swift version 5.11-dev (LLVM 54cbee1d059ba29, Swift 467f684a430cff0)
Target: x86_64-apple-macosx12.0
```

### Additional information

https://ci.swift.org/view/Dashboard/job/swift-main-source-compat-suite-debug/653/

**Comment by justice-adams-apple** [comment]
Xfailed: https://github.com/apple/swift-source-compat-suite/pull/879

**Comment by justice-adams-apple** [comment]
Looks related: https://github.com/apple/swift/pull/70907/
