### ISSUE TITLE
[Regression][5.7] "unable to infer closure type in the current context" when passing a member access expression as property wrapper argument inside closure

### ISSUE THREAD

**Issue by pablocornejo** [apple/swift#61024]
**Describe the bug**
Passing a member access expression (such as `SomeEnum.someCase.rawValue`, `SomeType().someProp`, etc.) as an argument to a property wrapper located inside a closure causes a compilation error on Swift 5.7, whereas it compiles correctly on Swift 5.6. 

The following code reproduces the issue:

```swift
@propertyWrapper
struct Wrapper {    
    var wrappedValue: Int
    let argument: String
    
    init(wrappedValue: Int, argument: String) {
        self.wrappedValue = wrappedValue
        self.argument = argument
    }
}

class Foo {
    let bar: () -> Void = {
        @Wrapper(argument: Baz.someCase.rawValue) // works on 5.6, errors out on 5.7
        var wrapped = 1
    }
}

enum Baz: String {
    case someCase
}
```

**Steps To Reproduce**
1. Add the code above to a Wrapper.swift file
2. Compile the file with the Swift 5.7 compiler: `$ swiftc Wrapper.swift`
3. The following compilation error occurs:
```
❯ swiftc Wrapper.swift
Wrapper.swift:13:27: error: unable to infer closure type in the current context
    let bar: () -> Void = {
                          ^
```

**Expected behavior**
Passing a member access expression that returns a type that is compatible with the property wrapper's parameter that it's being passed to should compile correctly when located inside a closure, as it does on Swift 5.6.

**Environment**
 - Xcode 14 RC toolchain (Swift 5.7)

**Additional context**
The code snippet above demonstrates the issue using an enum with a raw value, but it seems the issue happens with other member access expressions as well, such as:

```swift
class Foo {
    let bar: () -> Void = {
        @Wrapper(argument: Baz().someProp) // works on 5.6, errors out on 5.7
        var wrapped = 1
    }
}

struct Baz {
    let someProp: String = "someArg"
}
```
Also, this issue only seems to happen in closures, changing the closure declaration to a method with the same signature compiles correctly:

```swift
class Foo {
    func bar() {
        @Wrapper(argument: Baz.someCase.rawValue) // works on 5.6 and 5.7
        var wrapped = 1
    }
}
```

5.6 vs 5.7 compiler comparison here: https://godbolt.org/z/shEs56dhM

**Comment by xedin** [comment]
The problem here is related to pre-check - `buildPropertyWrapperInitCall` returns raw version of AST, in non-closure case `typeCheckExpression` is called on the resulting expression which runs pre-check internally. If property wrapper is declared in a closure the solution application application target for `var wrapped` init is mutated by `maybeApplyPropertyWrapper` after it has been pre-checked.
