### ISSUE TITLE
[Source compatibility suite] CoreStore failing to build with Swift 4.0

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#61905]
**Describe the bug**
The source compatibility suite project [CoreStore](https://github.com/JohnEstropia/CoreStore) is failing to build with swift 4.0 after recent compiler changes.

**Steps To Reproduce**
1. Build swift using the main branch
1. Checkout [CoreStore @ 2863605d845cd9bb255ddd91f47f92717dec637f](https://github.com/JohnEstropia/CoreStore/commit/2863605d845cd9bb255ddd91f47f92717dec637f) and attempt to build the project
The output will contain

```
swift-source-compat-suite/project_cache/CoreStore/Sources/NSManagedObjectContext+ObjectiveC.swift:80:55: error: cannot convert value of type 'NSFetchRequest<any NSFetchRequestResult & AnyObject>' to expected argument type 'NSFetchRequest<any NSFetchRequestResult>'
        fetchClauses.forEach { $0.applyToFetchRequest(fetchRequest) }
                                                      ^
```

This project is failing to build in both debug and release mode

**Expected behavior**
Expecting the project to build correctly

**Environment (please fill out the following information)**
https://ci.swift.org/job/swift-main-source-compat-suite-debug/247
