### ISSUE TITLE
[SR-15689] Invalid RangeReplaceableCollection regression with 5.6-dev

### ISSUE THREAD

**Issue by keith** [apple/swift#57968]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15689      |
   |Radar             | None         |
   |Original Reporter | @keith      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 624883e0e7e686d3859043c1e70fb36e

  </details>

**Issue Description:**

This code:

``` none
struct Foo<Element>: RangeReplaceableCollection {
    init() {}

    var startIndex: Int { fatalError() }
    var endIndex: Int { fatalError() }

    subscript(_ index: Int) -> Element { fatalError() }
    func index(after index: Int) -> Int { fatalError() }
}
```

Compiles fine with swift 5.5.2 (xcode 13.2.1)

But with 2021-12-23 main snapshot (org.swift.50202112231a) compiling gives these errors:

``` none
/tmp/foo.swift:1:8: error: type 'Foo<Element>' does not conform to protocol 'RangeReplaceableCollection'
struct Foo<Element>: RangeReplaceableCollection {
       ^
/tmp/foo.swift:1:8: error: unavailable instance method 'replaceSubrange(_:with:)' was used to satisfy a requirement of protocol 'RangeReplaceableCollection'
struct Foo<Element>: RangeReplaceableCollection {
       ^
Swift.RangeReplaceableCollection:4:26: note: 'replaceSubrange(_:with:)' declared here
    public mutating func replaceSubrange<C>(_ subrange: Range<Self.Index>, with newElements: C) where C : Collection, Self.Element == C.Element
                         ^
Swift.RangeReplaceableCollection:4:19: note: requirement 'replaceSubrange(_:with:)' declared here
    mutating func replaceSubrange<C>(_ subrange: Range<Self.Index>, with newElements: __owned C) where C : Collection, Self.Element == C.Element
                  ^
```

**Comment by glessard** [comment]
Correct, it is intentional. Any conformance that is broken by the change linked above would not have worked correctly.
